# Generated by Django 2.2.2 on 2019-10-21 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWeekStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('picks', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pick10.Player')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pick10.Week')),
            ],
            options={
                'verbose_name_plural': '9. PlayerWeekStats',
            },
        ),
    ]
