# Generated by Django 2.2.7 on 2019-12-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick10', '0002_auto_20191203_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerweekstat',
            name='defaulter',
            field=models.BooleanField(default=False),
        ),
    ]
